---
- name: Startup EKS Worker Nodes
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Include environment-specific variables
      include_vars: "vars/{{ env_name }}.yml"

    - name: Fetch Artifactory Credentials from Vault
      hashivault_read:
        secret: "secret/data/artifactory"
        token: "{{ vault_token }}"
      register: artifactory_creds

    - name: Download CSV from Artifactory
      uri:
        url: "https://artifactory.example.com/artifactory/path/to/{{ cluster_name }}_{{ env_name }}_nodegroup_details.zip"
        method: GET
        user: "{{ artifactory_creds.data.data.username }}"
        password: "{{ artifactory_creds.data.data.password }}"
        dest: /tmp/{{ cluster_name }}_{{ env_name }}_nodegroup_details.zip

    - name: Unzip the CSV file
      unarchive:
        src: /tmp/{{ cluster_name }}_{{ env_name }}_nodegroup_details.zip
        dest: /tmp/

    - name: Read CSV content
      read_csv:
        path: /tmp/{{ cluster_name }}_{{ env_name }}_nodegroup_details.csv
      register: csv_content

    - name: Iterate through CSV content and update ASG
      command: >
        aws eks update-nodegroup-config --cluster-name {{ cluster_name }} --nodegroup-name {{ item.NodeGroup }} --scaling-config minSize={{ item.MinSize }},maxSize={{ item.MaxSize }},desiredSize={{ item.DesiredCapacity }} --region {{ region }}
      with_items: "{{ csv_content.list }}"
      loop_control:
        loop_var: item

    - name: Uncordon EKS nodes
      command: >
        kubectl uncordon {{ item.NodeGroup }}
      with_items: "{{ csv_content.list }}"
